export PATH="$HOME/.local/bin:$PATH"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSHCFG="${HOME}/.config/zsh"

# Source in order
[[ -r "${ZSHCFG}/env.zsh" ]] && source "${ZSHCFG}/env.zsh"
[[ -r "${ZSHCFG}/plugins.zsh" ]] && source "${ZSHCFG}/plugins.zsh"
[[ -r "${ZSHCFG}/aliases.zsh" ]] && source "${ZSHCFG}/aliases.zsh"
[[ -r "${ZSHCFG}/functions.zsh" ]] && source "${ZSHCFG}/functions.zsh"
[[ -r "${ZSHCFG}/completion.zsh" ]] && source "${ZSHCFG}/completion.zsh"

# Local aliases (not in git, optional)
[[ -r "${ZSHCFG}/local.zsh" ]] && source "${ZSHCFG}/local.zsh"

# p10k config (generated by `p10k configure`)
[[ -r "${HOME}/.p10k.zsh" ]] && source "${HOME}/.p10k.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# vi mode module
if [ -f "$HOME/.config/zsh/vi-mode.zsh" ]; then
  source "$HOME/.config/zsh/vi-mode.zsh"
fi

# fnm
FNM_PATH="/opt/homebrew/opt/fnm/bin"
if [ -d "$FNM_PATH" ]; then
  eval "`fnm env`"
fi